import {LIST} from "./consts";

export const data = {
  [LIST.BASICS]: [
    "Passport/ID",
    "Cash",
    "Credit card",
    "Smart phone & charger",
    "Camera & charger",
    "Health/travel insurance card",
    "Itinerary/reservations",
  ],
  [LIST.CLOTHES]: [
    "Underwear",
    "Socks",
    "Bras",
    "Pyjamas",
    "T-shirts",
    "Pants",
    "Shorts",
    "Dresses",
    "Skirts",
    "Sweaters",
    "Swimsuits",
    "Coats/jackets/raincoats",
    "Laundry bag",
    "Leisure shoes",
    "Walking/sport shoes",
    "Sandals/flip-flops",
    "Hats",
    "Gloves",
    "Scarves",
    "Belts",
    "Jewelry",
    "Purses",
  ],
  [LIST.TOILETRIES]: [
    "Toothbrush",
    "Toothpaste",
    "Dental floss",
    "Deodorant",
    "Soap",
    "Shampoo",
    "Brush",
    "Skin lotion/cream",
    "Sunscreen",
    "Contact lenses/solution",
    "Shaving supplies",
    "Makeup",
    "Makeup remover",
    "Lip balsam",
    "Feminine-hygiene products",
    "Birth control",
    "Hand sanitizer",
    "First-aid kit",
    "Insect repellent",
    "Pain relievers",
    "Medications",
    "Travel towel",
  ],
  [LIST.OTHER]: [
    "Binoculars",
    "Sunglasses",
    "Laptop/tablet & charger",
    "Earphones/headphones",
    "Music player",
    "Books",
    "Board games",
    "Watter bottle",
    "Food/snacks/gum",
    "Travel pillow",
    "Travel blanket",
    "Eye mask & Ear plugs",
    "Tissues",
    "Guidebooks & Maps",
    "Paper & Pen",
    "Umbrella",
    "Cotton bag",
    "Copies of Passport/Tickets/etc.",
  ]
};