import { LIST } from "./consts"

export const lists = [
  {
    category: LIST.ESSENTIALS,
    title: "category.essentials",
    items: [
      "item.passport",
      "item.cash",
      "item.credit_card",
      "item.phone_charger",
      "item.insurance",
      "item.tickets",
      "item.copies",
    ],
  },
  {
    category: LIST.CLOTHES,
    title: "category.clothes",
    items: [
      "item.underwear",
      "item.socks",
      "item.bras",
      "item.pyjamas",
      "item.tshirts",
      "item.shirts",
      "item.pants",
      "item.shorts",
      "item.dresses",
      "item.skirts",
      "item.formal_clothes",
      "item.sport_clothes",
      "item.sweaters",
      "item.swimsuits",
      "item.coats",
      "item.shoes_formal",
      "item.shoes_leisure",
      "item.shoes_sport",
      "item.sandals",
      "item.flipflops",
      "item.hats",
      "item.gloves",
      "item.scarves",
      "item.belts",
      "item.ties",
      "item.jewelry",
      "item.purses",
      "item.towel",
      "item.laundry_bag",
    ],
  },
  {
    category: LIST.TOILETRIES,
    title: "category.toiletries",
    items: [
      "item.toothbrush",
      "item.toothpaste",
      "item.floss",
      "item.mouthwash",
      "item.deodorant",
      "item.soap",
      "item.shampoo",
      "item.hair_brush",
      "item.hair_bands",
      "item.hair_dryer",
      "item.hair_straightener",
      "item.cream_face",
      "item.cream_hand",
      "item.sunscreen",
      "item.lenses",
      "item.shaving",
      "item.makeup",
      "item.perfume",
      "item.lip_balsam",
      "item.earpicks",
      "item.feminine",
      "item.birth_control",
      "item.wet_wipes",
      "item.sanitizer",
      "item.first-aid",
      "item.repellent",
      "item.pain_killers",
      "item.medications",
      "item.laundry_kit",
    ],
  },
  {
    category: LIST.OTHER,
    title: "category.other",
    items: [
      "item.binoculars",
      "item.sunglasses",
      "item.camera_charger",
      "item.laptop_charger",
      "item.mp3_charger",
      "item.earphones",
      "item.powerbank",
      "item.books",
      "item.games",
      "item.bottle",
      "item.snack",
      "item.pillow",
      "item.blanket",
      "item.mask",
      "item.tissues",
      "item.guidebooks",
      "item.paper_pen",
      "item.umbrella",
      "item.locks",
      "item.flashlight",
      "item.bag",
    ],
  },
]
